local dap = require("dap")
-- dap.adapters.chrome = {
--   type = "executable",
--   command = "node",
--   args = { "/home/x/vscode-chrome-debug/out/src/chromeDebug.js" } -- TODO adjust
--   -- args = { "/home/x/vscode-chrome-debug/out/src/chromeDebug.js" } -- TODO adjust
--   -- args = { os.getenv("HOME") .. "/x/vscode-chrome-debug/out/src/chromeDebug.js" } -- TODO adjust
-- }
--
-- dap.configurations.javascriptreact = { -- change this to javascript if needed
--   {
--     type = "chrome",
--     request = "attach",
--     program = "${file}",
--     cwd = vim.fn.getcwd(),
--     sourceMaps = true,
--     protocol = "inspector",
--     port = 3000,
--     webRoot = "${workspaceFolder}"
--   }
-- }
--
-- dap.configurations.typescriptreact = { -- change to typescript if needed
--   {
--     type = "chrome",
--     request = "launch",
--     program = "${file}",
--     cwd = vim.fn.getcwd(),
--     sourceMaps = true,
--     protocol = "inspector",
--     port = 3000,
--     webRoot = "${workspaceFolder}"
--   }
-- }
--
-- dap.configurations.javascript = { -- change to typescript if needed
--   {
--     type = "chrome",
--     request = "attach",
--     program = "${file}",
--     cwd = vim.fn.getcwd(),
--     sourceMaps = true,
--     protocol = "inspector",
--     port = 3000,
--     webRoot = "${workspaceFolder}"
--   }
-- }
--
-- dap.configurations.typescript = { -- change to typescript if needed
--   {
--     type = "chrome",
--     request = "launch",
--     program = "${file}",
--     cwd = vim.fn.getcwd(),
--     sourceMaps = true,
--     protocol = "inspector",
--     port = 3000,
--     webRoot = "${workspaceFolder}"
--   }
-- }
