AGE_SECRET_KEY: ENC[AES256_GCM,data:WJJ899s5Eowxxhiet2CnXbF9s/onf0xQ5Ft1B/WZ/v5jLaP5gpON7DnTxTlWvm4z2FLy5BSFHSQF64LRRtikN1nHwaZswaVNeQFWRbgw+USDvloC78/6nkmazvPSeXE6mrHLXBEQF5EX7edwIVSqBOAD1ciD9xM+v0Qy3doSOgw3Syg6ak2+iNtRrEGCDdvMG84SyNtdXsIxHdC7uMIQynALaRtFSgJWd6rSOcwA6ugrBWqyNA8rhr8WZeM=,iv:J+gqijfP/cnLMAiimkx56g8PrLbycMql+k+p5uZYpCg=,tag:goGGOb8Mysy8LOw84J1q6A==,type:str]
CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:jZSAQ7b3AJp8L78dY0SeT/tmorp7SwJiWgDHM/mNsmvbaF14A4Aj/g==,iv:nruj09RWEo1SD1ar3/xX9UKtMKxB9YReMiNSZAYAX0I=,tag:DDQ1FVbYEg5E5GiLciwUkQ==,type:str]
ACME_VAULT_CERT_CREDENTIALS: ENC[AES256_GCM,data:fdT7FNRLKT+1jaDacDCUxWbCCtsqMcPw2ebWVFqguVxXpDj7Omw36Qfr5+QGNUtL78joJyM5HA23i8T+V+cTNaKWErh+CYAdjP9qqDz2hLojSqQX7BZFVWFqKh4vgeGuKpfO1xTEjyKpD1brqgkd1pEcaZE=,iv:2Ngt2HOolu6Z4W5EFgcXDwPe61zdFGqrzX50fSvqBFw=,tag:ReQ0pmPFZOly0h0rgI2b6Q==,type:str]
NOMAD_GOSSIP_ENCRYPTION_KEY.hcl: ENC[AES256_GCM,data:2EobCqU94tIpCf5lH8T5qNOjhkjLUzZRc7e1dknfvs9H3b5HrrgIgoR240sf6Bpi/6X0mn+AyVd+RKCdc1NaJvLzzxrs,iv:zUeUf/nGCS119dENlrpsnxtI9OpqQmD8T/B6Lc6mj6w=,tag:nAYJn2Sdgf2q6rhWVna8Fg==,type:str]
VICTORIA_METRICS_VAULT_TOKEN: ENC[AES256_GCM,data:/AQmVUsFcoc4mLNVSGm8j7A+PbuilZTOkQfvusogi/SC2ahPO+w8AnoOaZnk8eK4/6kbR7lGdPzXofaySjk+91yRQCj1GeieYxjCbtONlRCGT/EHxCo75SlAgV0xcjI=,iv:W38DefOzcPJOImoP/Nl4OF1Q/glgij3Zw8kBOoZFbp0=,tag:Yf/XNe62WG7C+w8U/o/wXQ==,type:str]
sops:
    age:
        - recipient: age168m4m55fh56t889x5tn8rfpntq0mzrk48u09zd57kdyrw8224quszj0kpc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0T3ByNGkvZ0dHUmtCSDlt
            amdHZFNEclNhNWFQVk56Tm0vTS9KR0JLZW5BCnoxbU5qQUZxbVc5R3hMYkhUV0lM
            NDZ5eVYxM0lHS2REM0lQZ2hmeXhHekEKLS0tIENvaUpKenlwZVJxV0djc3dUNXhE
            aldnaEpiYW1veVJMZmhsdDdxcEdkM1kKdqE4K8FEGkfogH6+rDHK3mxFFEQyG32y
            hq/09G8ertezZPJ7ZeMWtM1rXbB4hjkTAnr29Qluc9O8nKWjCxFgmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-30T10:01:21Z"
    mac: ENC[AES256_GCM,data:vmSyMmZ4X/TQYbMSr9raA5J4yX4xDJ/2ZoZ/p15Y4JcSM0Op1eqGgQA8skPdLRtzaaNc83TkC/blryXwQyoEhpHWrKfuM3LktU8X0eAIKGdh2bRqg6Unrih7hiM6BchvD0JWZR8ib3coEB8/EPqwF5Qbz2FiOU6GKOYW/tyn5+I=,iv:8mDMiYe2M1zngQQTcs1MF3x69fjiv9QZWf/O+JYoQwI=,tag:HoSpYsKeHSkUKsqQ/ltAnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
