AGE_SECRET_KEY: ENC[AES256_GCM,data:e/htubQfqD+vdM/NyPpkmUXGq7wGcOR5xWvwgjEUC4TJibp8+4kgOcQ4G77QPzeatPAcYkRJl5zVb167b2vP216r4DKRq1rsXMq7EPDW7SX+TvsiXwOd3CBGVsozzU2sCWZ1JrACl2HdQlW4IoKoRvWH3+oFIM/I0kWVon5ZOdcrhcEmFpNqGjh9PWN6CR2h4D3+Ks1pWPLWzVHu3L90z/b9T1+raRVYY2SGT4lCjCEmtobVRUJ7vvJCrCc=,iv:CHnTz4PMdNEB1m8FsM8hkRLeCGf2TRj2F2b9vjZQ2Xg=,tag:6XiXC7yt2a+MhURmIas7Ug==,type:str]
CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:nnYMvwYS6UoE9JB/uRSH2cyQscHo7vcFtoZUfQ6J6pFVT3Owv5eSIaCUQ9JULw6KmzLf+jzGiwfuseSJ9g==,iv:RcQlWP4u0mC8Bdam3UKSD6lq/O/U/71IlFnPi/8NoIU=,tag:dxzdu+3hu2N9Q6Y4PAy1Lg==,type:str]
ACME_VAULT_CERT_CREDENTIALS: ENC[AES256_GCM,data:mW4WVzWbO7Ka/PidlI7m/9r6cPN7nBUrnhkngccS6fMM/fpZHSYvJBNMtZwOwazSVkanB7Av/8+CWr/vNhvgxFIUeC9GaVVfYt1fU0GJW55Lz4iF1umV/bDdyrpl4hxPddUDlPuPEzDc0lTU/6buntkrIOI=,iv:mxDh+HsaWjaoDpxVlz6JqGRPXlnQt4D2ENwKbzWLOsk=,tag:Tn4Hb9ZLlbcfmtqOVQSXeQ==,type:str]
NOMAD_GOSSIP_ENCRYPTION_KEY.hcl: ENC[AES256_GCM,data:uAgsi1ltg3KS6DUpxhtN8YUgqgvPJua3gXdnw2K4OlIGC0aXZhelP4Nb32kgpAI/mYyZrr8SkWhtaZ1BoBHBslNPtnIp,iv:D6c6yV8KOYTEiJ83r5mLE69i0C4jP0sOoRY3yodv8fQ=,tag:nfMeS8Ezu95vlWjVQuBJ0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168m4m55fh56t889x5tn8rfpntq0mzrk48u09zd57kdyrw8224quszj0kpc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocVlJWG5LOGJLWEJVWE9v
            ck9wRUFpYkhmL2dKeXpqUldadXE1NmdiWFZRCkV5SkJ1YzZvaldRbU1SOUFQWXhC
            aWN2MFZCeG1MNE1FK1V0ZVNBSkR4UUUKLS0tIFFrTnJvZEtWNmg5WStGWmtjT1d0
            Mk5mQ3BzekJ0Z3d3TndQWWhOejdVWEUKPJj+QN8oX50YwvdEYmHUgHSGFVmj6lym
            FxFJzQoI3STECy2P1foLqOBNiS0JgNlFddRqQonEtreuux+VMulnSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-08T23:45:18Z"
    mac: ENC[AES256_GCM,data:299sQgUD7XPmuFNpL20XMtyC1opKHVxiyv8CKO5grBCI0xzXy39Ps1JbWrpCG/lVS7hAwW8B7SpbA+VmhGCy8wuha8IEWB75Zzd3S6Cw1vPMmdh5D6FgGyLrHUUH76k57XaFELC4Di5fpD18AO6IAcTlSxjWpPYLa6g+6ghUA7U=,iv:TX+4YuqUFwdXcHm5pROFk3wNsEBzqp/dGkiUAGbaeXs=,tag:PdERSIJb9dFwU/LOrVZ6wg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
