#ENC[AES256_GCM,data:gCOIeqU=,iv:c2M6O6ZanD26cS3txy6RdGHBhsundvBjZrtnggB1VZM=,tag:zOK1INFzwTZFaPeGceWAeQ==,type:comment]
AGE_SECRET_KEY: ENC[AES256_GCM,data:D+PTd6+H8O5blkmihYGoDrU3qfDHcSAEvzHHhQiNx3Py/TzEkS1vaWhoYTlMt6UKmFEAnN8mzx+Ok+6b662qvTclnArWQeW0k8y5Bhfm6lxAit3OLmtKy6IXYVABhUH3NCdRvt1UEy1D+at9n9Valjo66ZTxwwQe0fm5MCdlwtJl+23BaM8Qk73G8VMmvtSiNxkfOp5cnzpTuv4I1dKY/RRRftaJF2P4LRLDqqx9A/hMZaAdiN0cQiXfpw8=,iv:Sn3hjLE/luJTuzxi13wszuVcbLaIUgZQWag8stY1fwA=,tag:6Lat9Yb/pGSQtjHenWIUzA==,type:str]
#ENC[AES256_GCM,data:RSWl9xk=,iv:YchJKoePFlR8EOoUV4UGAzH79BF9aTLND7srC26jjjY=,tag:zeVQuulXAw1JqB1dBSaV9A==,type:comment]
CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:6T+nEkOGk4fCe8PjmhUyVxDJic4rs9OxKfe1hUHizdEeDmAV3xLM3cuE18MEjzyj5SHXiy6Xf4htpBjg5Q==,iv:SRJ+ymMJzicdkaghg3UEF+iAcRZEIl8XMkeS235HFSk=,tag:gaFTLW/qqPDlX/kEZgPBig==,type:str]
#ENC[AES256_GCM,data:PHNhhRI=,iv:4EW4OG6a1s22hdSvtcVehbmZXdJ7cLSOK0BZ72MDCOg=,tag:0PJOTclRi9edGz0oBid0oQ==,type:comment]
ACME_VAULT_CERT_CREDENTIALS: ENC[AES256_GCM,data:Ea9Q8JYRqimd4Dp/SepFeUMdG+jHLUfoHI5xr4I7sQdf4JhLySnSbG3rOtABAQjImq0NCrfAUBXFt/PgR7l7jfus7B5bR2GL1Q/libzg7RVeBJSKGMIl3Eheg6FP6fWeLtgs6vcOerFcpa0rC11fLPohEp4=,iv:2l6t73ynpcNTJ5pm63mzNW7K8xrkmNTmdgUv9S8x6Cc=,tag:4erh4g8vZFrggSfnB8uQoQ==,type:str]
#ENC[AES256_GCM,data:tnj+Fyo=,iv:DUBap4mhhidWiYAVEUKnQ3c/4kkRE7cQ1Y1YJ54Ev3M=,tag:P6vSc+1kN2K4ap8aoEiprA==,type:comment]
NOMAD_GOSSIP_ENCRYPTION_KEY.hcl: ENC[AES256_GCM,data:6gePLpgj6xA3N6cfZ62wk45LAAutm2bSRdKZWBrKTDU0iyF+L6FnpPXlPeNzrDkMLQeCJ6pJgOLCHwv9Ow1bedGpcIh2,iv:mewIsUKWR83313M08hwFqQcoiMFj4axEq6chlMs/Hlk=,tag:LE3CEGovU232F7QLcLVDGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168m4m55fh56t889x5tn8rfpntq0mzrk48u09zd57kdyrw8224quszj0kpc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUE5PdGl5TkV6OWxlYzRP
            Vjdjd3l3a2tlc2tGRlVjWWJIejdzSWJVb1MwCkNWM0Z6T2ZLMDB1dGpmcXBza3Vw
            T1p2TmxHYnlZQVM5VnVML25BNWxRN1UKLS0tIEFaWk9DMGFQRmFMNitxdURySDZm
            UFBIYngwM2ZCRVdKczZWSkVITERjbEEK4/94ah9u3VW5S0FtWsaqzASLvGJkJqYY
            N+hIL4uCTTQZ+SvqL/JOfOPwjnqTgvQUtTXN8rRr3VkRqTmT39ySEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-08T20:47:35Z"
    mac: ENC[AES256_GCM,data:/fmHTpR615gGnOjaz2y6P5Wu9l1ZQAqaVeM8AeRlRXPCA6MkwWc6gwII4PTBG7T5SmyYgsNYIcX7nrSUW8mp6lIBadf7jyjmCzH4rXO3bPp+YdSNstGYMYsaEromPSFfRnjHfSl+Ru2mHkDXKSEa9bEzgEZpexCPJ82Pd8e7oNE=,iv:tnla5B1x5T2tIVoVzq9/KsO116Y7AAAd81/FSa3+p6o=,tag:f6I/HG/tmbG8cFR1FHbXdA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
