AGE_SECRET_KEY: ENC[AES256_GCM,data:nkPkLai7nbJZaO+Ab+2ftBKqgBPve+n1l8/OArBX/8lBue7ff2racTNn9wMsCd/QzkcX9ZyVzH+NwP+F48G5uFQsAMx6QCRP5LJ6exy6gI/bCkXfFlSKxqZVsQsT6jtIJyBCKheqUqAHDkeMk5fGz/O33BLWqO1wmtWmX1pR8FcdbjLCrDOxs/ttos6jzOBmxkq8kDr9urhLOByHyDt8iu+GToAoWezzJfJ2gPo73YUD8CE91cYWTXnLZFw=,iv:tybAsIx8/5vQ2ViL/WcSzsUqV5/ouBOJjX4B4xLABmo=,tag:fpZhWO4CcZWkosPy2F29XA==,type:str]
CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:aN6xDOy45O6rduNgeRT25FUmjIr7hifiyA6he6K7eSrPWjp7ASJvSNpTC3CtFIKflNWpyPZN255BG/v+2w==,iv:iFCBXru0t5q3cQ7StLJNJbLlH8iguF0ePiuQSj/oZ04=,tag:S50rks/Y3v+K7kkv060khA==,type:str]
ACME_VAULT_CERT_CREDENTIALS: ENC[AES256_GCM,data:zc55U+ODwA795NsesdInjZuIScKZoxwWkvKLNMu16jTzjT9FTKmlx+fEhT55MtiTWHODmX7Etl+zHqZ9aEPMZpB3wpGKGOghmY0zA8LvWaVjzfMqcwmSHtD64jkcgg1QkAzeUEz0MrUBHUOtm3BYIP127PI=,iv:bM4TOFRzBS1fOMRqchrHGb5I54PnnTQpa4EIw6ddNQ8=,tag:KPjF7M7x2gn93tujaVNS3A==,type:str]
NOMAD_GOSSIP_ENCRYPTION_KEY.hcl: ENC[AES256_GCM,data:7xT4NFzQEGtgqOslAWvgzthTRTy2Z56ZXn2tecu2Gc9SJpH5j8LN+oi2XGC/De0tE5wQ1QsKwcgCgdDEI02OwgSI9WAj,iv:hTlQDZR/2knv2ntaU6ikA6LMMVM0CbslsFfr/OWp4EM=,tag:YOac/mLB9GGkDgCAzViHXw==,type:str]
VICTORIA_METRICS_VAULT_TOKEN: ENC[AES256_GCM,data:xYBRpezVW2Hhax9orQQ1ufoBwxtfztcmTLsBJuzWLkYbfgWGPrtcxhY641+dYANJq/IweJBW+gpWvt7vRenE2zYXTv1mybpsuZ3VmV6V0RuxMCY4cfT2ZiBBQYAkPd4=,iv:SoHgWZcukOf1rTHDwn6n6aUuT9pju5l0HAJ+RRvYDj4=,tag:HLbxLu62UEP8yl1rXWw6XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168m4m55fh56t889x5tn8rfpntq0mzrk48u09zd57kdyrw8224quszj0kpc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRkg5MDM1K2pSblJ0MDVo
            SjNmaW9LYU9qTDUxR3VlZ1Q3TFNsenNIQTJzCmZjeU83QVdRVGQ5SldEZDZzcExS
            Sy96WjZVYVR0V3B5ZEFJdWhuRXIxc2MKLS0tIG0vQmJRenBiSlViejlCT1cvNW94
            YVJhU0VJSGpqOER4WU5DbndraFdNWlEKWCnSbnVzSz20uGp1Q0NRsrdlIT4QmRrg
            jEzBqBUfw+dvHvIPmEpFbjvcZ0EU3ezEs6i6c9T6zTXaoN6Cpc3Htg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-10T20:47:23Z"
    mac: ENC[AES256_GCM,data:AkJVWAkYlxIz4SMS6/2T757oZz0P5dnpSUitQc0o0j+eH9O74iRlbm3Bz+Ktw6D3NQdngU1jLaEIvZNUHmBLc+La9gdK2hZbIws9/HpPhV3MzUz3mwJYUYdW82BRsKjPACuIVq17JbtlbCWCxjQzR5tCfxdC+SQXbkt6uk6NW3I=,iv:aaqiKTsVk+39gxX2Tdm/cO3U8albQ4eUr73zDdFmY2g=,tag:6kVy7rjvwWN2vJy26Yk4Fg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
